name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

# Cancel any in-progress runs of this workflow if a new push happens on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install Dependencies
        run: npm ci
      - name: Check Style
        run: npm run eslint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright Browsers
        # run: npx playwright install chromium
        # run: npx playwright install
        run: npx playwright install --with-deps
        # run: npx playwright install --with-deps chromium -- to install deps of only chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
